### ISSUE TITLE
Cannot search in episodes newer than 1188

### ISSUE THREAD

**Issue by jncosideout** [mcclymont/nasearch-ruby#12]
Since about the beginning of the year, users have noticed that the "To Show" search bar's placeholder text stopped updating at 1201. I have run a recent test search on the keyword "trump" where "From Show" = 1100, and "To Show" = 1202 and I only got results up to show 1187. You would expect to get results from nearly every episode from around 750 (2015) to close 1231 (the most recent episode at the time of this writing).

**Comment by mcclymont** [comment]
Hi @jncosideout. Apologies for such a delay. I'm looking into fixing these issues now. Thanks for reporting it here

**Comment by mcclymont** [comment]
Fixed. Waiting on Adam to set DNS of search.nashownotes.com
