### ISSUE TITLE
Integrate with Searx api

### ISSUE THREAD

**Issue by adamc199** [mcclymont/nasearch-ruby#4]
I would be great to contribute our info to the Searx metasearch engine. They have an api. https://asciimoo.github.io/searx/

**Comment by amirtoole** [comment]
Hey @mcclymont 
I have a “working” integration with searx and your search api here:
https://github.com/hellofornow/searx/commit/00449d9d042f599c2e825276299451626012c562
I’ve had to hardcode an X-CSRF token (obv won’t be a stable sol’n).

I just found this repo so I’ll poke around, but any ideas on how we would be able to leverage your search api without validating our session?
I was also thinking of adding the album art for a specific show; but that can be achieved in a separate pr.

**Comment by mcclymont** [comment]
I'm going to close this since @hellofornow seems to have a solution

I have removed the CSRF token requirement
