### ISSUE TITLE
Search Not Working for Recent Episodes

### ISSUE THREAD

**Issue by loffelmacher** [mcclymont/nasearch-ruby#6]
A user reports that "search.nashownotes.com no longer lets you search up to the current show. The max is episode 1135"

**Comment by mcclymont** [comment]
Thanks for reporting. Seems that http://feed.nashownotes.com/ changed quite substantially which broke the periodic updater rake task.

Should be fixed now

https://github.com/mcclymont/nasearch-ruby/commit/eb2f46d88698d01d5c7662271efcfb10ddea4a53
